---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tls-lab-auth-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.middlewares: training-lab-lab-auth@kubernetescrd
  namespace: training-lab
spec:
  rules:
    - host: tls-auth-nginx.LABSERVERNAME
      http:
        paths:
        - path: /
          backend:
            serviceName: lab-nginx-service
            servicePort: 80
  tls:
   - secretName: traefik-ui-tls-cert

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: lab-auth
  namespace: training-lab
spec:
  basicAuth:
    secret: lab-secret